### ISSUE TITLE
HQ camera?

### ISSUE THREAD

**Issue by fpgasdr** [Billwilliams1952/microVIEW#4]
Hello, I have a raspberry pi 4 and the new HQcamera and running your code I got this error:

Traceback (most recent call last):
  File "microVIEW.py", line 1554, in <module>
    Run_microVIEW()
  File "microVIEW.py", line 1537, in Run_microVIEW
    microVIEW(microVIEWApp,camera,language,appTitle,width,height)
  File "microVIEW.py", line 258, in __init__
    self.ResolutionChanged(res[Globals.defaultResolution])
IndexError: list index out of range

it seems the resolution I have is not correct because default res for Q camera is outside the range.

if I modify the res array to include the extra resolutions when run the code i get for 1 second I can see the menu but then it disappears. and only get a black screen and don't know what to do. 

I have a TFT screen 480x320 resolution but running also with vnc with 1280x800 get the same results.

any workaround?.

Thanks.

**Comment by jpfy** [comment]
For the HQ Camera I added this line at 252
`elif self.camera.revision == "testc": 	#HQ Camera
			res.append('Ultra: (4056x3040)')`
after `if self.camera.revision == "imx219": 	# V2 camera
			res.append('Max Photo: (3280x2464)')`

This works
